server:
  port: ${PORT:9090}

spring:
  main:
    banner-mode: off

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    # 使用TiDB Cloud数据库
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/fortune500?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true
    username: 2eXmMXiGeCt9iz7.root
    password: 00KpH8EmSBk7A3ET
    # Druid连接池配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


  cache:
    type: simple
    # redis: removed

# 文件上传路径配置
file:
  upload-path: ${UPLOAD_PATH:./uploads/}



# JWT
jwt:
  user-secret-key: ${JWT_USER_SECRET_KEY:wray12121212asdhiashdikasbdiasgfiabgfkbaiwfgiwfawfafa}
  user-ttl: 172800000   # 2 天
  user-token-name: Authorization

features:
  rakuten:
    enabled: true

# MyBatis Plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:**/mapper/*.xml
  type-aliases-package: com.wray.hjzdm.entity
  global-config:
    banner: off

# Knife4j
knife4j:
  enable: true

# =========================
# 第三方商品平台配置
# =========================

rakuten:
  app-id: ${RAKUTEN_APP_ID:1065081596741280321}
  application-secret: ${RAKUTEN_APPLICATION_SECRET:d3cea25fd388a80da369ee74a20e67c9c4b00625}
  affiliate-id: ${RAKUTEN_AFFILIATE_ID:4f0e084a.2fb02d14.4f0e084b.3ecf281e}

yahoo:
  client-id: ${YAHOO_CLIENT_ID:dmVyPTIwMjUwNyZpZD1LUlpMQm80aVNUJmhhc2g9TVdJME1ERTRNVFJrTkdJMk1ESmpaQQ}
  secret: ${YAHOO_SECRET:8TwrbIHTWFS5Zk6tyOBQLVHdOQQ6g3XEnQmU70SO}

