const axios = require('axios');

// Configure base URL - change if needed
const baseURL = 'http://localhost:9090';

const client = axios.create({
  baseURL,
  timeout: 5000
});

async function run() {
  try {
    console.log('Starting test run...');
    
    // Generate random user details
    const timestamp = Date.now();
    const username = `testuser_${timestamp}`;
    const email = `test${timestamp}@example.com`;
    const password = 'password123';
    
    console.log(`Creating user: ${username} / ${email}`);

    // 1. Register
    // Endpoint: /user/register
    // Payload: UserRegisterDTO(username, email, password, confirmPassword)
    let token = '';
    let userId = 0;
    
    try {
      const registerRes = await client.post('/user/register', {
        username: username,
        email: email,
        password: password,
        confirmPassword: password
      });
      
      console.log('Register response:', JSON.stringify(registerRes.data, null, 2));
      
      if (registerRes.data.code === 200 && registerRes.data.data) {
        token = registerRes.data.data.token;
        userId = registerRes.data.data.id;
        console.log(`Registered successfully. Token: ${token.substring(0, 20)}..., UserID: ${userId}`);
      } else {
        console.error('Registration failed to return token/id');
      }
      
    } catch (e) {
      console.error('Register failed:', e.response ? e.response.data : e.message);
      
      // If register failed, maybe try login (in case we re-run)
      // But for unique timestamps this shouldn't happen often unless rapid re-runs
    }

    // 2. Login (if registration didn't give token or just to verify login works)
    if (!token) {
        try {
            console.log('Attempting login...');
            const loginRes = await client.post('/user/login', {
                username: username,
                password: password
            });
            console.log('Login response:', JSON.stringify(loginRes.data, null, 2));
            if (loginRes.data.code === 200) {
                token = loginRes.data.data.token;
                userId = loginRes.data.data.id;
            }
        } catch (e) {
            console.error('Login failed:', e.response ? e.response.data : e.message);
            return;
        }
    }

    if (!token) {
        console.error('Could not get token. Aborting.');
        return;
    }

    // 3. Add Disclosure
    // Endpoint: /disclosure/add
    // Payload: Disclosure(title, content, link, disclosurePrice, imgUrl)
    console.log('Adding disclosure...');
    try {
        const addRes = await client.post('/disclosure/add', {
            title: `Test Disclosure ${timestamp}`,
            content: 'This is a test disclosure content generated by script.',
            link: 'http://example.com/product/123',
            disclosurePrice: 99.99,
            imgUrl: 'http://example.com/image.jpg'
        }, {
            headers: { 'Authorization': token }
        });
        console.log('Add Disclosure response:', JSON.stringify(addRes.data, null, 2));
    } catch (e) {
        console.error('Add Disclosure failed:', e.response ? e.response.data : e.message);
    }

    // 4. Query My Disclosure (User View)
    // Endpoint: /disclosure/queryMyDisclosure
    console.log('Querying My Disclosures...');
    try {
        const myRes = await client.post('/disclosure/queryMyDisclosure', {
            pageNum: 1,
            pageSize: 10
        }, {
            headers: { 'Authorization': token }
        });
        console.log('My Disclosures result:', JSON.stringify(myRes.data, null, 2));
        
        const list = myRes.data.data; // PageInfo or List
        if (Array.isArray(list)) {
            console.log(`Found ${list.length} disclosures.`);
        } else if (list && list.records) { // MyBatis Plus Page object
             console.log(`Found ${list.records.length} disclosures.`);
        } else if (list && Array.isArray(list.list)) { // PageHelper PageInfo
             console.log(`Found ${list.list.length} disclosures.`);
        }
        
    } catch (e) {
        console.error('Query My Disclosures failed:', e.response ? e.response.data : e.message);
    }

    // 5. Query Pending List (Admin View)
    // Note: Usually requires admin rights, but let's see if we can query it or if we need to login as admin.
    // The user said "when I log in with admin account".
    // For this test, we might not be able to query pending list if it requires admin role.
    // But let's try with the current user first.
    console.log('Querying Pending List (as current user)...');
    try {
        const pendingRes = await client.post('/disclosure/queryPendingList', {
            pageNum: 1,
            pageSize: 10
        }, {
            headers: { 'Authorization': token }
        });
        console.log('Pending List result:', JSON.stringify(pendingRes.data, null, 2));
    } catch (e) {
        console.error('Query Pending List failed:', e.response ? e.response.data : e.message);
    }

    // If we have an admin account (e.g. id=1 or name=admin), we could try that too.
    // Let's assume we don't have the password for 'admin' handy unless hardcoded or default.
    // So we rely on the backend logs for now.

  } catch (e) {
    console.error('Unexpected error:', e);
  }
}

run();
